[package]
name = "veda-ft-query"
version = "0.1.1"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
nng = "1.0.0"
serde_json = "1.0"
futures = "=0.3"

version = "3.0.0"
git-version = "0.3.9"

v_common = { package = "v-common", version = "=0.10.6" }
#v_common = { package = "v-common", path = "../../../v-common" }

