[package]
name = "veda-input-onto"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2021"

[[bin]]
name = "veda-input-onto"
path = "src/main.rs"

[dependencies]
log = "0.4"
ron = "0.5.1"
serde = "1.0"
notify = "=4.0.17"
md-5 = "0.8.0"
hex = "0.4.0"
crossbeam-channel = "0.5.1"
rio_turtle = {git="https://github.com/semantic-machines/rio.git", rev="a3e887c58980b1e4b3519750da168ccf1c6f0fab"}
rio_api = {git="https://github.com/semantic-machines/rio.git", rev="a3e887c58980b1e4b3519750da168ccf1c6f0fab"}

v_common = { package = "v-common", version = "=0.4.54" }
#v_common = { package = "v-common", path = "../../../v-common" }

